pusher/pusher-websocket-java

- src/main/java/com/pusher/client/Pusher.java
- src/main/java/com/pusher/client/channel/impl/ChannelManager.java
- src/test/java/com/pusher/client/PusherTest.java
- src/test/java/com/pusher/client/channel/impl/ChannelManagerTest.java
**Allow unsubscribe while disconnected**
Actually Pusher class throws an Exception when trying to unsubscribe from a Channel and the connection state is not CONNECTED. This can lead to issues implementing automatic reconnection because when Pusher.connect() is invoked, the library tries to re-subscribe to previouslly created channels, basically subscribing to a channel which nobody is interested to anymore.
With the proposed change, if the status is not CONNECTED the channel is only removed from the map and it will not re-subscribed again at the next connection attempt.
**Ignore unsubscribe request from not subscribed channels**
Just a small improvement to improve tolerancy against developer mistakes. If for any reason a developer invoke `Pusher.unsubscribe()` twice with the same channel …
> Allow unsubscribe while disconnected

- src/main/java/com/pusher/client/Pusher.java
- src/main/java/com/pusher/client/PusherOptions.java
- src/main/java/com/pusher/client/channel/ChannelEventListener.java
- src/main/java/com/pusher/client/channel/PresenceChannel.java
- src/main/java/com/pusher/client/channel/SubscriptionEventListener.java
- src/main/java/com/pusher/client/channel/User.java
- src/main/java/com/pusher/client/connection/Connection.java
- src/main/java/com/pusher/client/connection/ConnectionEventListener.java
- src/main/java/com/pusher/client/connection/ConnectionStateChange.java
- src/main/java/com/pusher/client/util/HttpAuthorizer.java
@leggetter As promised :smile: 
This PR fixes all javadoc warnings and errors in the 0.4.0-release branch. Most of the errors/warnings were due to:
- `.` rather than `#` was being used to link to methods - see http://www.oracle.com/technetwork/articles/java/index-137868.html
- no `@param` or `@return` tag or tag description
- `<p>...</p>` was being used for the first JavaDoc paragraph - JavaDoc automatically treats the first block as a paragraph so adding the `<p>` tag generates a warning. From http://www.oracle.com/technetwork/articles/java/index-137868.html - `The first sentence of each doc comment should be a summary sentence`
- `<ul>...</ul>` tags were inside of `<p>...</p>` blocks - Not allowed in HTML so JavaDoc fails (http://stackoverflow.com/a/10601411/2634854)
> fixing javadoc warnings and errors

- src/main/java/com/pusher/client/util/HttpAuthorizer.java
HashMap is unnecessary here and since it is not needed, users should be able to use other implementations of Map.
> use generic Map for HttpAuthorizer

- .gitignore
- src/main/java/com/pusher/client/channel/impl/ChannelImpl.java
Following on from #71 
Locking around both the `eventNameToListenerMap` and `listeners` HashSet.
> Fix binding unbinding concurrent modification

- build.gradle
Fix for https://github.com/pusher/pusher-websocket-java/issues/80. I've tested this by deploying to a maven repo on my local disk but I can't see anything that would cause it to not work when deploying to an authenticated repo.
> add classifiers to tasks that generate archives

- src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java
- src/test/java/com/pusher/client/channel/impl/PresenceChannelImplTest.java
All IDs are now strings, resolving issues where Gson would cast numbers as doubles before making them a string. 
`Presence`, `PresenceData` and `MemberData` types now created, instead of using `Map`s
:100: :rocket:
> Create presence and member data objects

- CHANGELOG.md
- build.gradle
- src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java
Takes the work done by @siggijons in #86 and prepares for a v.1.0.2 release.
The test supplied in #86 hasn't been included since it only works in isolation so isn't suitable as a regression test. It was used to manually verify the fix. All existing tests continue to pass so existing functionality remains the same.
> v1.0.2 release

- src/main/java/com/pusher/client/channel/impl/ChannelManager.java
get() on a Map object returns null if the key does not exist.
> Removed superfluous code

- src/main/java/com/pusher/client/PusherOptions.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketClientWrapper.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
- src/main/java/com/pusher/client/util/Factory.java
- src/test/java/com/pusher/client/EndToEndTest.java
- src/test/java/com/pusher/client/PusherOptionsTest.java
- src/test/java/com/pusher/client/TestWebSocketClientWrapper.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketClientWrapperTest.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java
* Forward a `setProxy` method in `PusherOptions` on to the underlying java-websocket connection
* + Rename 'proxy' in WebsocketClientWrapper to 'websocketListener' to avoid confusion
Tests coming up...
> Create setProxy method in options.

- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
> Make connection event listeners concurrent hashmap. Resolves #97

- src/main/java/com/pusher/client/channel/User.java
- src/main/java/com/pusher/client/channel/impl/ChannelImpl.java
- src/main/java/com/pusher/client/channel/impl/ChannelManager.java
- src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
There are a lot of operations that occur upon construction of a `Gson` object so it seems wrong to be allocating such an object upon each piece of JSON received by the client or sent to your servers. This puts the allocation of a single `Gson` object in `Factory` so that a single instance can reused across the usage of a `Pusher` object.
> Reduce construction of Gson objects and keep one centralized instance in Factory

- src/main/java/com/pusher/client/Pusher.java
Fix a few small typos in the javadoc.
> Fix small typos in javadoc.

- src/main/java/com/pusher/client/connection/websocket/WebSocketClientWrapper.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
- src/main/java/com/pusher/client/util/Factory.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketClientWrapperTest.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java
The underlying WebSocketClient connection will attempt to perform a WebSocket compliant graceful shutdown.
But in the case where a disconnect was called due to the client not receiving a pong, this will likely not succeed, which would delay the change to DISCONNECTED.
> Immediately set connection state to disconnected due to a pong timeout

- src/main/java/com/pusher/client/util/HttpAuthorizer.java
While strictly incorrect (201 describes the creation of a new HTTP
resource, the URI of which is reported in the Location header), some
other client libraries have long accepted 201 responses, and people have
tested their implementations only with such libraries.
@jpatel531
> Accept 201 status code from auth endpoints

- README.md
> Update readme with the latest version

- src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java
Removing unneeded parsing of payload into a JSON object
https://github.com/pusher/pusher-websocket-java/issues/122
Primary reasoning is that iOS doesn't do this, so why restrict Android's functionality
> Removing unneeded parsing to JSON

- src/main/java/com/pusher/client/channel/impl/ChannelManager.java
- src/test/java/com/pusher/client/channel/impl/ChannelManagerTest.java
This would avoid the ConcurrentModificationException if unsubscribe/subscribe happens when connecting to the channel.
> Synchronise access to channelNameToChannelMap

- README.md
> Always specify cluster when instantiating pusher

- .travis.yml
- build.gradle
- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
Everything from https://github.com/pusher/pusher-websocket-java/pull/156 plus remove on travis oraclejdk7 that was deprecated
----
> Remove dependency on slf4j-api in favor of JUL

- README.md
- build.gradle
JavaDoc and sources we published were the other way around. This fixes it.
----
> Correct javadoc and sources

- src/main/java/com/pusher/client/util/ConnectionFactory.java
- src/main/java/com/pusher/client/util/HttpAuthorizer.java
- src/main/java/com/pusher/client/util/UrlEncodedConnectionFactory.java
Note: this is a continuation of PR #165, but aims at tidying up the code as requested by @zmarkan  
By subclassing ConnectionFactory and passing a new instance into the HttpAuthorizer class, it is now possible to send JSON objects in the body, rather than only "Content-Type: application/x-www-form-urlencoded" strings.
Users can also set the correct headers to be sent - for example "Content-Type: application/json", and are able to override the "charset" header as well.
#164
----
> Enable additional body types for POST authorization

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/pusher/client/PusherOptions.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
- src/main/java/com/pusher/client/util/Factory.java
- src/test/java/com/pusher/client/EndToEndTest.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java
To make configurable the connection number of reconnection attempts.
(Copied over with a typo fix from https://github.com/pusher/pusher-websocket-java/pull/174)
In a server-mode use, hard-coded 6 reconnection attempts is not enough.
> Configurable reconnections

- src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java
Adds a null check to ids list before iterating in for loop.  Fixes https://github.com/pusher/pusher-websocket-java/issues/183
On Android 7 and 8 we've recently seen a spike in crashes from inside the 1.8 pusher SDK. We have seen NullPointerException when iterating through this list of ids. Related issue https://github.com/pusher/pusher-websocket-java/issues/183
----
> NPE fix when iterating through ids in the SubscriptionSuccessfulMessage

- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java
Currently, the library ignores Pusher codes and therefore attempts reconnections. I have a feeling this will cause issues with future feature work we may do, so here's a fix.
Respecting protocol.
----
> Don't reconnect when codes in 40xx range are received

- README.md
Add the section about how to test the library locally with Android Studio
> change readme about testing locally

- CHANGELOG.md
- README.md
This reverts commit 5adb33c4d18b454ec346699e2c4fec60be21235b.
This was intended to go into a PR that isn't ready for merge yet.
...
...
----
> Revert "readme changes"

- build.gradle
- src/main/java/com/pusher/client/connection/websocket/WebSocketClientWrapper.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketListener.java
- src/main/java/com/pusher/client/example/SimpleWebSocket.java
- src/test/java/com/pusher/client/EndToEndTest.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketClientWrapperTest.java
In https://github.com/pusher/pusher-websocket-java/commit/569b765e5955842b7fac699a07c11ee6c9c04a38, we switched from using https://github.com/TooTallNate/Java-WebSocket to a fork https://github.com/pusher/java-websocket because the original was not actively maintained.
I've manually tested the change in an Android app.
https://github.com/TooTallNate/Java-WebSocket is now actively maintained again. We'd rather not maintain a fork.
----
> Switch back to non-forked version of java-websocket

- CHANGELOG.md
- README.md
- build.gradle
Based on the changes made in this commit: https://github.com/pusher/pusher-websocket-java/commit/d46b30becabc3d4899b4c6270cfb8708f6e1e73c.
The CHANGELOG has already been updated.
> v2 release

- gradle/wrapper/gradle-wrapper.properties
The combination of this gradle version, the signing plugin and the
legacy maven plugin seem to cause the error:
Execution failed for task ':signArchives'.
Duplicate key pusher-websocket-java:jar.asc:asc: (attempted merging values Signature pusher-websocket-java:jar.asc:asc: and Signature pusher-websocket-java:jar.asc:asc:)
There is not much information about this online, except for
https://github.com/gradle/gradle/issues/8213 and
https://discuss.gradle.org/t/apply-plugin-signing-broke-in-gradle-5-1-1-and-prints-out-non-existent-task/31418
Switching to the recommended maven plugin `maven-publish` might
solve this problem, but that will be more work, so downgrading
gradle is a better option in the short term.
----
> Downgrade gradle to 5.0

- README.md
Remove publish instructions
These are only relevant to Pusher employees, and have been moved to internal documentation.
----
> Remove publish instrucitons

- src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java
- src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java
- src/test/java/com/pusher/client/channel/impl/PresenceChannelImplTest.java
- src/test/java/com/pusher/client/channel/impl/PrivateChannelImplTest.java
If the auth endpoint returns channel_data, then this should be
forwarded to the auth endpoint even if it is not used by private
channels currently.
This is useful because it allows the same auth endpoint to be
used for private and presence channels.
It also avoids confusing auth signature errors that occur when the
channel_data is not sent (but the auth signature was computed from
it).
Fixes #144.
In order to support the getMe() method on PresenceChannel, we need
to store the channel_data in the PrivateChannelImpl class. This
is decoded in the PresenceChannelImpl class since presence channels
require the channel_data is JSON. It is decoded in toSubscribeMessage()
rather than getMe() to preserve the original semantics (e.g.
exceptions cannot be thrown from getMe().
----
> Forward channel data on private channels

- src/main/java/com/pusher/client/connection/ConnectionStateChange.java
- src/test/java/com/pusher/client/connection/ConnectionStateChangeTest.java
We currently fail hard when a state update to the current state is requested.  This change simply logs the error instead, for debugging.
There are clearly situations where this _can_ happen (issue #218) and is more likely to happen on newer devices (assuming there's a race condition).
> Make a no-op state change non-fatal

- .travis.yml
- README.md
- build.gradle
Added Jacoco plugin to generate test reports. 
Updated the travis.yml to generate the tests and send them to codecov.
...
This enables codecov to post in PRs to let us know if we're increasing or decreasing code coverage at all (hopefully)
...
> CI codecov reports

- build.gradle
- src/main/java/com/pusher/client/util/Base64.java
- src/test/java/com/pusher/client/crypto/nacl/SecretBoxOpenerTest.java
> Decrypt test

- src/main/java/com/pusher/client/util/Base64.java
- src/test/java/com/pusher/client/util/Base64Test.java
> Add Base64 char validation

- build.gradle
- src/main/java/com/pusher/client/util/internal/Base64.java
- src/test/java/com/pusher/client/crypto/nacl/SecretBoxOpenerTest.java
- src/test/java/com/pusher/client/util/Base64Test.java
Simplify exclude rules making it more clear they refer
to package names not file paths relative to project's root.
> Exclude Base64 class from Javadoc

- src/main/java/com/pusher/client/channel/PrivateEncryptedChannelEventListener.java
- src/main/java/com/pusher/client/channel/impl/ChannelImpl.java
- src/main/java/com/pusher/client/channel/impl/InternalChannel.java
- src/main/java/com/pusher/client/channel/impl/PrivateEncryptedChannelImpl.java
- src/main/java/com/pusher/client/example/PrivateEncryptedChannelExampleApp.java
- src/test/java/com/pusher/client/channel/impl/PrivateEncryptedChannelImplTest.java
* Decrypts messages - we convert the received data into a `EncryptedReceivedData` object - we then replace the `data` part of the JSON with the decrypted message and pass it back to be packaged as a PusherEvent.
* Retries only once if we can't decrypt it - if we can't decrypt it a second time we notify the listeners of an `onDecryptionFailure` - I have an open Q about what sort of Exception we should be returning here.
* Added a `prepareEvent` method in the base Channel class which converts the json to the PusherEvent class, but this is where we can hook into decrypting it without having to copy all the other logic to handle messages.
* Added a `getInterestedListeners` to get all the interested listeners for an event - we needed this in the ChannelImpl to notify when a message is …
> Dev decrypt plus retry

- README.md
- src/main/java/com/pusher/client/example/PrivateEncryptedChannelExampleApp.java
> Private Encrypted Channels docs

- CHANGELOG.md
- README.md
- build.gradle
- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java
The `disconnect` method is public, and tests the current state before
taking action, scheduling this work to happen on the event thread.
However, when a pong times out, the `onClose` is executed immediately,
transitioning in to the reconnecting state before the scheduled
disconnect happens, meaning disconnect fails to take any action and
potentially resulting in the old connection not being torn down.
----
> Do not use the disconnect method to tear down on pong timeout

- CHANGELOG.md
- README.md
- build.gradle
- src/main/java/com/pusher/client/PusherOptions.java
- src/main/java/com/pusher/client/example/ExampleApp.java
- src/main/java/com/pusher/client/example/PresenceChannelExampleApp.java
- src/main/java/com/pusher/client/example/PrivateChannelExampleApp.java
- src/main/java/com/pusher/client/example/PrivateEncryptedChannelExampleApp.java
- src/test/java/com/pusher/client/PusherOptionsTest.java
Refactor PusherOptions `forceTLS` to `useTLS`
...
We want to be consistent with our public interface between client sdks
...
----
> Refactor PusherOptions forceTLS to useTLS

- README.md
- src/main/java/com/pusher/client/example/PrivateEncryptedChannelExampleApp.java
Removing the beta label over the private encrypted channels docs.
Do not merge this PR until private encrypted channels is actually released 🎉
> Remove beta label from private encrypted channel docs

- build.gradle
Updated the Java-WebSocket dependency to 1.5.1.
...
It was reported to us that in #279 that there is a vulnerability in the current version of the dependency and we should update asap
...
> Update Java-WebSocket dependency to 1.5.1

- src/main/java/com/pusher/client/channel/impl/PrivateEncryptedChannelImpl.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketClientWrapper.java
Issue #283 when we updated the websocket library.
I could reproduce this crash myself with an emulator running 5.1 and the current version of the library.
I followed the [instructions on the websocket library](https://github.com/TooTallNate/Java-WebSocket/wiki/No-such-method-error-setEndpointIdentificationAlgorithm) to fix this issue. There was a discussion around the issue for those interested [here](https://github.com/TooTallNate/Java-WebSocket/issues/1011). And the [public interface](https://github.com/TooTallNate/Java-WebSocket/blob/1.5.1/src/main/java/org/java_websocket/client/WebSocketClient.java#L526) has been documented.
I have also surrounded the call super method with a try so android 24+ devices can get the benefit.
I have tested on my emulator that this version does not crash …
> Fix websocket issue with pre android sdk 24 devices

- README.md
We want to remove the android wrapper - let's start by not linking to it and just telling people this library works perfectly fine 🤖
> remove link to android wrapper

- src/main/java/com/pusher/client/channel/SubscriptionEventListener.java
- src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java
- src/test/java/com/pusher/client/channel/impl/PresenceChannelImplTest.java
> Return error via SubscriptionListener when presence events are malformed

- README.md
Clicking on the link produce an error:
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
...
...
----
> Should use https

- README.md
In the README section about running the example application, the jar file name is incorrect. This updates the README to the correct jar file.
The current file name doesn't exist after a build.
----
> Use correct jar file name in README.md

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Update gradle wrapper from 5.0 to 7.3.
This required:
* Migrating from the deprecated maven plugin to maven-publish
* Removing the deprecated jcenter repository
* Replacing deprecated gradle features with equivalent modern ones (plugin declarations, dependency specifications, ...)
* Updating jacoco
Gradle 5 conflicted with newer versions of the jdk, which prevented us from using them locally for development.
----
> Update gradle wrapper from 5.0 to 7.3

- build.gradle
Upgrade jacoco to 0.8.8.
It adds support for java 17 and 18, making it possible to test with them locally.
----
> Upgrade jacoco to 0.8.8

- src/main/java/com/pusher/client/Pusher.java
- src/main/java/com/pusher/client/channel/impl/BaseChannel.java
- src/main/java/com/pusher/client/channel/impl/ChannelImpl.java
- src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java
- src/main/java/com/pusher/client/channel/impl/message/SubscribeMessage.java
- src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java
- src/main/java/com/pusher/client/user/User.java
- src/main/java/com/pusher/client/user/impl/InternalUser.java
- src/main/java/com/pusher/client/user/impl/ServerToUserChannel.java
- src/main/java/com/pusher/client/user/impl/message/AuthenticationResponse.java
- src/main/java/com/pusher/client/user/impl/message/SigninMessage.java
- src/main/java/com/pusher/client/util/Factory.java
- src/test/java/com/pusher/client/EndToEndTest.java
- src/test/java/com/pusher/client/PusherTest.java
- src/test/java/com/pusher/client/channel/impl/ChannelImplTest.java
- src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java
- src/test/java/com/pusher/client/user/impl/InternalUserTest.java
Add support for user signin and server to user messages.
Significant changes are:
* New User and InternalUser interface and class are introduced. These contain the main logic
* Channel implementation code was moved into an abstract BaseChannel, so that it could be reused for the ServerToUserChannel
* Event handling code was moved out of the connection that now takes in a eventHandler function. There's also a change in behaviour there that all events are passed to this event handler.
Rolling out support for the new user features to more SDKs.
----
> Add support for user signin and server to user messages

- README.md
Change Gradle's `compile` to `implementation`.
compile has been disabled in Gradle 7: https://docs.gradle.org/current/userguide/declaring_dependencies.html#sub:project_dependencies
https://tomgregory.com/gradle-implementation-vs-compile-dependencies/
> Update readme for adding deps

- README.md
Mention specific Android versions in the supported platforms section. Also cleanup Java versions.
Previously we didn't specify Android versions, but Android 5/6 will require additional steps which I've linked to.
I've trimmed down the Java versions to just the LTS versions to keep the list short.
> Android versions in readme supported platforms

- CHANGELOG.md
- README.md
- build.gradle
- src/main/resources/META-INF/proguard/pusher.pro
Add a proguard setting file excluding pusher.client classes from minifying.
Workaround for https://github.com/pusher/pusher-websocket-java/issues/333
- [FIXED] Fix issue with json serialization when using proguard
> Add proguard file

- CHANGELOG.md
- README.md
- build.gradle
- src/main/resources/META-INF/proguard/pusher.pro
Tighten the proguard rules to fewer classes.
`-keep class com.pusher.client.** { *; }` is too broad.
- [CHANGED] pusher.pro narrower proguard rules.
> Narrower proguard rules
