CHANGELOG.md, README.md
Will hang on this until we've resolved whether the version should be `0.4.0` or `1.0`
=> Update readme for new release. Add linked TOC. Resolves #77 and #67

.travis.yml, README.md, build.gradle
Basic CI covering jdk 7 and 8. Will consider adding more targets in future
=> Add travis

src/main/java/com/pusher/client/util/Factory.java
=> Synchronize queueOnEventThread

src/main/java/com/pusher/client/connection/ConnectionState.java, src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java, src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java
Added retry logic that starts reconnecting when server closes the connection
Follow maximum number of reconnect attempts, otherwise transition to disconnected, and exponentially increase the wait before reconnecting.
Added the retry connecting condition for when the app is in CONNECTING state.
Added  unimplemented tests for the reconnection logic
=> Add Reconnecting logic when you lose connectivity.

README.md, build.gradle
=> Update readme to 1.7.0

README.md
Method was renamed on https://github.com/pusher/pusher-websocket-java/commit/4de5e6fc71e993dd60ac60a26b0860fbb694f91b but not updated in the README.
----
=> update method name

README.md
It seemed weird that we didn't talk about any of this in the readme, so I added it.
To improve visibility of what the library can do.
=> Add PusherOptions documentation

README.md
Pusher is now called Pusher Channels
=> Pusher is now called Pusher Channels

README.md
Add supported versions of Java to clarify what we do and don't support.
=> Add supported versions of Java

CHANGELOG.md, README.md, build.gradle
=> Release version 2.0.2

src/main/java/com/pusher/client/crypto/nacl/Poly1305.java, src/main/java/com/pusher/client/crypto/nacl/Salsa.java, src/main/java/com/pusher/client/crypto/nacl/SecretBoxOpener.java
Only automatic fixes that surely looked safe applied.
=> Fix warnings in NaCl

src/main/java/com/pusher/client/example/ExampleApp.java, src/main/java/com/pusher/client/example/PresenceChannelExampleApp.java, src/main/java/com/pusher/client/example/PrivateChannelExampleApp.java, src/main/java/com/pusher/client/example/PrivateEncryptedChannelExampleApp.java
Document and tidy up the example apps
...
Hopefully it'll make it easier for people to run and learn how to use 😄 
...
----
=> Document Example Apps

CHANGELOG.md, README.md, build.gradle
=> Prepare release 2.2.4

src/main/java/com/pusher/client/Client.java, src/main/java/com/pusher/client/channel/impl/ChannelImpl.java, src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java, src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java, src/main/java/com/pusher/client/connection/websocket/WebSocketClientWrapper.java, src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java, src/main/java/com/pusher/client/connection/websocket/WebSocketListener.java, src/main/java/com/pusher/client/example/SimpleWebSocket.java, src/main/java/com/pusher/client/util/HttpAuthorizer.java, src/test/java/com/pusher/client/EndToEndTest.java, src/test/java/com/pusher/client/PusherOptionsTest.java, src/test/java/com/pusher/client/PusherTest.java, src/test/java/com/pusher/client/channel/PusherEventTest.java, src/test/java/com/pusher/client/channel/impl/ChannelImplTest.java, src/test/java/com/pusher/client/channel/impl/ChannelManagerTest.java, src/test/java/com/pusher/client/channel/impl/PresenceChannelImplTest.java, src/test/java/com/pusher/client/channel/impl/PrivateChannelImplTest.java, src/test/java/com/pusher/client/channel/impl/PrivateEncryptedChannelClearsKeyTest.java, src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java, src/test/java/com/pusher/client/util/HttpAuthorizerTest.java
Fixed a bunch of the easier linting issues.
=> Fix Linting Warnings

CHANGELOG.md, README.md, build.gradle
This PR:
- Prepares for the v2.2.6 release
=> Release v2.2.6

.github/workflows/ci.yml, build.gradle
Updating to the latest version of gson
...
fixing vulnerabilities 
...
----
=> Update gson version

src/main/java/com/pusher/client/channel/Channel.java, src/main/java/com/pusher/client/channel/impl/ChannelImpl.java, src/test/java/com/pusher/client/channel/impl/ChannelImplTest.java, src/test/java/com/pusher/client/channel/impl/PrivateEncryptedChannelImplTest.java
This PR adds the functionality to bind to all events.
...
...
----
=> Add global event listner

CHANGELOG.md, README.md, build.gradle
=> change log

build.gradle
Replace tabs with spaces. Consistent string quoting
Not super necessary, but it's one less commit in my next PR (and I want to test a github integration).
----
=> Reformat build.gradle

src/main/java/com/pusher/client/Client.java, src/main/java/com/pusher/client/channel/impl/ChannelImpl.java, src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java, src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java, src/main/java/com/pusher/client/connection/websocket/WebSocketClientWrapper.java, src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java, src/main/java/com/pusher/client/connection/websocket/WebSocketListener.java, src/main/java/com/pusher/client/example/SimpleWebSocket.java, src/main/java/com/pusher/client/util/HttpAuthorizer.java, src/test/java/com/pusher/client/EndToEndTest.java, src/test/java/com/pusher/client/PusherOptionsTest.java, src/test/java/com/pusher/client/PusherTest.java, src/test/java/com/pusher/client/channel/PusherEventTest.java, src/test/java/com/pusher/client/channel/impl/ChannelImplTest.java, src/test/java/com/pusher/client/channel/impl/ChannelManagerTest.java, src/test/java/com/pusher/client/channel/impl/PresenceChannelImplTest.java, src/test/java/com/pusher/client/channel/impl/PrivateChannelImplTest.java, src/test/java/com/pusher/client/channel/impl/PrivateEncryptedChannelClearsKeyTest.java, src/test/java/com/pusher/client/connection/websocket/WebSocketConnectionTest.java, src/test/java/com/pusher/client/util/HttpAuthorizerTest.java
Our gradle wrapper was quite old, I also removed any unused plugins and updated as many warnings as I could.
We still have an issue with the maven publish - we might want to [look into this](https://discuss.gradle.org/t/mavendeployment-deprecated-with-gradle-6-3/36096) at somepoint to resolve the final warnings.
=> Code cleanup

.github/workflows/ci.yml
Test on the latest version too.
----
=> Add java 18 to ci

CHANGELOG.md, README.md, build.gradle
Updating version numbers and CHANGELOG for release.
Release.
----
=> Prepare for 2.3.0-beta release

build.gradle
See title.
Sources and javadoc are required to make a release.
----
=> Ensure gradle publish includes sources and documentation

build.gradle
=> Update version in gradle to 2.4.1

README.md, build.gradle
Bumping version in readme and gradle file.
Release 2.4.2
----
=> Prepare for 2.4.2 release

.github/get_staging_repository_id.py, .github/workflows/release.yml
Automate package release in nexus.
- [CHANGED] Package release automated.
=> Automate package release
